// Package showcasestrings — переводы демонстрационного приложения showcase.
//
// Пакет общий для двух витрин: оконной (cmd/showcase) и браузерной
// (cmd/webshowcase) — они показывают ОДНУ И ТУ ЖЕ разметку, поэтому и таблица
// строк у них одна.
//
// strings_ru.go — таблица строк РАЗМЕТКИ (СГЕНЕРИРОВАНО инструментом
// localize_xaml из прежнего русского showcase.xaml).
//
// Ключ — английская строка: в EN-режиме Tr не находит таблицу и возвращает сам
// ключ, поэтому английский текст не дублируется отдельной таблицей. Русский
// текст живёт здесь, а разметка ссылается на ключи через {Loc …}.
//
// Файл собран инструментом localize_xaml из прежнего русского showcase.xaml.
package showcasestrings

import "github.com/oops1/headless-gui/v3/widget"

// showcaseRU — переводы интерфейса showcase на русский.
var showcaseRU = map[string]string{
	"(click the header to collapse)":                  "(сворачивается по клику)",
	"1000 items — only visible rows are materialised": "1000 элементов — материализуются только видимые строки",
	"16 bit":         "16 бит",
	"32 bit":         "32 бит",
	"A (nested top)": "A (вложенный верх)",
	"A different style. Background, border and text — all of it is set from XAML.": "Другой стиль оформления. Фон, рамка и текст — всё настраивается через XAML.",
	"A long text with word wrapping (TextWrapping=Wrap). The headless-gui engine wraps words pixel-precisely to the container width. That makes it possible to build information panels and dialogs with dynamic content.": "Длинный текст с переносом строк (TextWrapping=Wrap). Движок headless-gui поддерживает пиксельно-точный перенос слов по ширине контейнера. Это позволяет создавать информационные панели и диалоги с динамическим содержимым.",
	"A panel with CornerRadius=8 and a border. Alpha transparency is supported.": "Панель с CornerRadius=8 и рамкой. Поддержка alpha-прозрачности.",
	"About":          "О программе",
	"Action":         "Действие",
	"Add record":     "Добавить запись",
	"Add row (live)": "Добавить строку (live)",
	"Address:":       "Адрес:",
	"Administrator":  "Администратор",
	"Age ≥ 30":       "Возраст ≥ 30",
	"AnimateRect: the panel flies between positions (EaseOutBack — with a slight overshoot).": "AnimateRect: панель летает между позициями (EaseOutBack — с лёгким «выбросом»).",
	"Animation framework (easing curves, engine-owned clock)":                                 "Анимационный фреймворк (easing-кривые, часы у движка)",
	"Animations": "Анимации",
	"Another block of text. Default font, light background for contrast. A wrapping check at various sizes.": "Ещё один блок текста. Шрифт по умолчанию, светлый фон для контраста. Проверка переноса при различных размерах.",
	"Antialiased graphics":              "Сглаженная графика (antialiasing)",
	"Any text to try the input...":      "Любой текст для проверки ввода...",
	"Arabic (ligatures, joined forms):": "Арабский (лигатуры, связные формы):",
	"Archive":                           "Архив",
	"Audio redirection":                 "Перенаправление звука",
	"Audio settings":                    "Аудио настройки",
	"Authentication method:":            "Метод аутентификации:",
	"Auto-update":                       "Авто-обновление",
	"B (nested bottom)":                 "B (вложенный низ)",
	"Backup:":                           "Резервное копирование:",
	"Balloon notifications (system, Shell_NotifyIcon · NIF_INFO):": "Balloon-уведомления (системные, Shell_NotifyIcon · NIF_INFO):",
	"Balloon: error":   "Balloon: ошибка",
	"Balloon: info":    "Balloon: инфо",
	"Balloon: warning": "Balloon: предупреждение",
	"Bindings · styles · triggers · commands": "Привязки · стили · триггеры · команды",
	"Budget.xlsx":                     "Бюджет.xlsx",
	"Button in a Grid (ColumnSpan=2)": "Кнопка в Grid (ColumnSpan=2)",
	"C (right panel)":                 "C (правая панель)",
	"Cancel":                          "Отмена",
	"Card 1":                          "Карточка 1",
	"Card 2":                          "Карточка 2",
	"Cell (1,0)":                      "Ячейка (1,0)",
	"Cell (1,1)":                      "Ячейка (1,1)",
	"Certificate (X.509)":             "Сертификат (X.509)",
	"Clear the log":                   "Очистить журнал",
	"Collapse/restore the left pane":  "Коллапс/восстановить левую",
	"CollectionView + virtualisation": "CollectionView + виртуализация",
	"Colour depth:":                   "Цветность:",
	"Colour emoji (COLR/CBDT, automatic in text):": "Цветные эмодзи (COLR/CBDT, авто в тексте):",
	"Colour glyphs are blitted as RGBA instead of being tinted with the text colour. Symbols outside the emoji block (❤ ✓ ✗ ⚠) stay monochrome by design; regional flags and COLRv1 gradients are known limitations.": "Цветные глифы блитятся как RGBA, не красятся цветом текста. Символы вне emoji-блока (❤ ✓ ✗ ⚠) остаются одноцветными по дизайну; региональные флаги и COLRv1-градиенты — известные ограничения.",
	"Command + shortcut":             "Команда + горячая клавиша",
	"Comment:":                       "Комментарий:",
	"Compress transferred data":      "Сжатие данных при передаче",
	"Connect automatically on start": "Автоматическое подключение при запуске",
	"Connection":                     "Подключение",
	"Containers":                     "  Контейнеры",
	"Context menu (right click)":     "Контекстное меню (справа)",
	"Control elements":               "  Элементы управления",
	"Controls":                       "Управление",
	"Copy":                           "Копировать",
	"Ctrl+Z — undo · Ctrl+Y — redo · double click — select word":             "Ctrl+Z — отменить · Ctrl+Y — повторить · двойной клик — выделить слово",
	"Curve race: six bars start together (900 ms), each with its own curve.": "Гонка кривых: шесть баров стартуют одновременно (900 мс), каждый со своей кривой.",
	"Cut":                                "Вырезать",
	"Dark theme":                         "Тёмная тема",
	"Data":                               "Данные",
	"DataTrigger will colour the status": "DataTrigger покрасит статус",
	"Delete":                             "Удалить",
	"Devanagari (conjuncts):":            "Деванагари (конъюнкты):",
	"Dialog larger than the window":      "Диалог больше окна",
	"Dialogs":                            "Диалоги",
	"Disable":                            "Отключить",
	"Disabled":                           "Отключено",
	"Display":                            "Дисплей",
	"Display settings":                   "Настройки дисплея",
	"DockManager — docking panels (Visual Studio style toolbox)": "DockManager — докинг-панели (Toolbox в стиле Visual Studio)",
	"Docking":       "Докинг",
	"Documentation": "Документация",
	"Done. The layout can be saved and restored with the buttons below.":                                                                                            "Готово. Раскладку можно сохранить и восстановить кнопками ниже.",
	"Drag a panel by its title bar — the dock guides appear; 📌 collapses the panel into a tab at the edge (auto-hide); the window button makes the panel floating.": "Тяни панель за заголовок — появятся направляющие дока; 📌 сворачивает панель в ярлык у края (auto-hide); кнопка-«окошко» делает панель плавающей (float).",
	"Drag and drop files from the OS (drag files from the file manager into the frame):":                                                                            "Drag & Drop файлов из ОС (перетащи файлы из проводника в рамку):",
	"Drag the bars with the mouse (the cursor changes), double click a bar to collapse or restore it. On the left there is a nested vertical split.":                "Тяни полосы мышью (курсор меняется), двойной клик по полосе — коллапс/восстановление. Слева — вложенный вертикальный сплит.",
	"Drop files here — their paths will appear":                                                                                                                     "Перетащите сюда файлы — появятся их пути",
	"E-mail (must contain @):":      "E-mail (обязательно «@»):",
	"Edit":                          "Правка",
	"Enter an address containing @": "Введите адрес с @",
	"Enter the password...":         "Введите пароль...",
	"Error":                         "Ошибка",
	"Every dialog is internal (the engine draws it over the dimmed background), so dialogs work headless and in streaming, and file dialogs show the server file system. The look follows the application theme (try switching the theme in the header) and the labels are localised (the Language button in the header switches RU/EN live). In a MessageBox: Enter — default button, Esc — cancel, Ctrl+C — copy the contents.": "Все диалоги — внутренние (движок рисует их поверх затемнения), поэтому работают в headless/стриминге и файловые диалоги показывают ФС сервера. Оформление следует теме приложения (попробуйте сменить тему в шапке), подписи локализованы (кнопка «Язык» в шапке переключает RU/EN вживую). В MessageBox: Enter — кнопка по умолчанию, Esc — отмена, Ctrl+C — копирование содержимого.",
	"Exit":            "Выход",
	"Explorer":        "Обозреватель",
	"Export settings": "Экспорт настроек",
	"Export...":       "Экспорт...",
	"File":            "Файл",
	"File dialogs (the file system of this process):": "Файловые диалоги (файловая система процесса):",
	"Font smoothing":                     "Сглаживание шрифтов",
	"Fractional, step 0.5":               "Дробное, шаг 0.5",
	"Full screen":                        "Полноэкранный режим",
	"Grid 4×3 (Grid with ShowGridLines)": "  Сетка 4×3 (Grid с ShowGridLines)",
	"Guest":                              "Гость",
	"Hebrew (RTL):":                      "Иврит (RTL):",
	"Hello":                              "Привет",
	"Hello 🙂 👍 🎉 🚀 🔥 👨\u200d👩\u200d👧 ⭐": "Привет 🙂 👍 🎉 🚀 🔥 👨\u200d👩\u200d👧 ⭐",
	"Help": "Справка",
	"High": "Высокое",
	"Hover the application button on the taskbar — the thumbnail and Aero Peek show the live window content (not a black rectangle).": "Наведите указатель на кнопку приложения в панели задач — во всплывающей миниатюре и в Aero Peek видно живое содержимое окна (а не чёрный прямоугольник).",
	"INFORMATION":             "ИНФОРМАЦИЯ",
	"IP address or host name": "IP или имя хоста",
	"Image quality:":          "Качество изображения:",
	"Indicators":              "  Индикаторы",
	"Information":             "Информация",
	"Input":                   "Ввод данных",
	"Input and progress:":     "Ввод и прогресс:",
	"Input data":              "  Ввод данных",
	"Installing updates:":     "Установка обновлений:",
	"Integer 0..100, step 1":  "Целое 0..100, шаг 1",
	"Invalid input → red border and a tooltip with the error text": "Неверный ввод → красная рамка + подсказка с текстом ошибки",
	"ItemsControl + DataTemplate (live)":                           "ItemsControl + DataTemplate (живой)",
	"Language: RU":                                                 "Язык: RU",
	"Latin and Cyrillic take the fast per-rune path; the shaper only kicks in for scripts that need it.": "Латиница и кириллица идут быстрым per-rune путём; шейпер включается только для скриптов, которым он нужен.",
	"Layout":              "Компоновка",
	"Lists":               "  Списки",
	"Loading data:":       "Загрузка данных:",
	"Login:":              "Логин:",
	"Low":                 "Низкое",
	"Max. 10 characters:": "Макс. 10 символов:",
	"MaxLength=10; Ctrl+Z/Ctrl+Y; double click — word": "MaxLength=10; Ctrl+Z/Ctrl+Y; двойной клик — слово",
	"Medium": "Среднее",
	"MessageBox (severity icon, Ctrl+C copies as on Windows):": "MessageBox (значок severity, Ctrl+C копирует как в Windows):",
	"Minimise to tray":            "Свернуть в трей",
	"Mixed LTR + RTL (bidi):":     "Смешанный LTR + RTL (bidi):",
	"Multiline TextBox":           "Многострочный TextBox",
	"Name: Report.docx":           "Имя: Отчёт.docx",
	"New":                         "Новый",
	"New connection":              "Новое подключение",
	"Notes.txt":                   "Заметки.txt",
	"Notifications":               "Уведомления",
	"One-time password (OTP)":     "Одноразовый пароль (OTP)",
	"Open":                        "Открыть",
	"Open file…":                  "Открыть файл…",
	"Operator":                    "Оператор",
	"Option 1":                    "Опция 1",
	"Option 2":                    "Опция 2",
	"Output":                      "Вывод",
	"Panel content":               "Содержимое панели",
	"Password:":                   "Пароль:",
	"Paste":                       "Вставить",
	"Plain text (single line)":    "Обычный текст (одна строка)",
	"Playback volume:":            "Громкость воспроизведения:",
	"Polygon / Line (width 1–5):": "Polygon / Line (толщина 1–5):",
	"Port number":                 "Номер порта",
	"Port:":                       "Порт:",
	"Price:":                      "Цена:",
	"Progress (indicator)":        "Прогресс (индикатор)",
	"Properties":                  "Свойства",
	"Protocol:":                   "Протокол:",
	"Quality (%):":                "Качество (%):",
	"Quantity:":                   "Количество:",
	"Question (Yes/No)":           "Вопрос (Да/Нет)",
	"Quick connect":               "Быстрое подключение",
	"Ready · Widget Showcase · headless-gui": "Готов · Widget Showcase · headless-gui",
	"Recording volume:":                      "Громкость записи:",
	"Rectangle (RadiusX — AA corners):":      "Rectangle (RadiusX — AA-углы):",
	"Remember credentials":                   "Запомнить учётные данные",
	"Report.docx":                            "Отчёт.docx",
	"Reset":                                  "Сброс",
	"Reset the form":                         "Сбросить форму",
	"Resolution: 1280×900":                   "Разрешение: 1280×900",
	"Restore layout":                         "Восстановить раскладку",
	"Retry":                                  "Повторить",
	"Russian":                                "Русский",
	"SVGIcon — themeable vector icons":       "SVGIcon — темизируемые векторные иконки",
	"Save":                                   "Сохранить",
	"Save as…":                               "Сохранить как…",
	"Save layout":                            "Сохранить раскладку",
	"Scale 100%":                             "Масштаб 100%",
	"Scale 150%":                             "Масштаб 150%",
	"Scale: 100%":                            "Масштаб: 100%",
	"Select all":                             "Выделить всё",
	"Select folder…":                         "Выбрать папку…",
	"Server":                                 "Сервер",
	"Server settings":                        "Настройки сервера",
	"Shortcuts":                              "Горячие клавиши",
	"Show menu":                              "Показать меню",
	"Sign in":                                "Войти",
	"Size: 128 KB":                           "Размер: 128 КБ",
	"Smooth progress: AnimateValue travels to a random target (a plain SetValue is instant).": "Плавный прогресс: AnimateValue едет к случайной цели (обычный SetValue — мгновенный).",
	"Sort A→Z":     "Сортировать A→Я",
	"Sound":        "Звук",
	"Speed (FPS):": "Скорость (FPS):",
	"SplitPanel — panes with a draggable splitter":                 "SplitPanel — панели с перетаскиваемым разделителем",
	"Standard dialogs (theme · localisation · Ctrl+C · Enter/Esc)": "Стандартные диалоги (тема · локализация · Ctrl+C · Enter/Esc)",
	"Status bar": "Строка состояния",
	"Switch UI language / Переключить язык интерфейса": "Переключить язык интерфейса / Switch UI language",
	"Switch the theme":                 "Сменить тему оформления",
	"Symbols ✓ ✗ ⚠ ▲ ▼ →":              "Символы ✓ ✗ ⚠ ▲ ▼ →",
	"System":                           "Система",
	"TabControl (nested)":              "TabControl (вложенный)",
	"Taskbar preview:":                 "Превью в панели задач:",
	"Text and graphics":                "Текст и графика",
	"Text input":                       "Ввод строки",
	"Text shaping (HarfBuzz, pure Go)": "Шейпинг текста (HarfBuzz, чистый Go)",
	"TextBox: MaxLength · Undo/Redo · double click": "TextBox: MaxLength · Undo/Redo · 2×клик",
	"Thai (mark positioning):":                      "Тайский (mark positioning):",
	"The animation clock belongs to the engine: not a single goroutine and not a single timer per animation — ticks come from the render loop, frames are rendered only while an animation is alive (the on-demand saving stays), and repainting is partial. Starting an animation again on the same object replaces the previous one (owner-replace), so animations never fight. The toggles on the Widgets tab slide, dialogs fade in; in the classic Win2000 theme everything is instant.": "Часы анимаций принадлежат движку: ни одной горутины и ни одного таймера на анимацию — тики идут в рендер-цикле, кадры рендерятся только пока анимация живёт (on-demand экономия сохраняется), перерисовка частичная. Повторный запуск на том же объекте заменяет прежнюю анимацию (owner-replace) — «дерущихся» анимаций не бывает. Тумблеры на вкладке «Виджеты» скользят, диалоги появляются с fade-in; в классической теме Win2000 всё мгновенно.",
	"The document area is the centre of the DockManager (SetCenter). An editor or a document viewer usually lives here.": "Документная область — центр DockManager (SetCenter). Здесь обычно живёт редактор или просмотрщик документа.",
	"The icon stays in the tray: double left click restores the window, right click opens the menu.":                     "Иконка остаётся в трее: двойной левый клик — восстановить, правый клик — меню.",
	"The result will appear here": "Результат появится здесь",
	"The tray icon is installed at startup (a blue square with a white G). The tray menu (right click): Show / Minimise / Balloon / Exit — it renders in its own popup window at the cursor, so it appears even when the main window is hidden. Drag and drop: native on Win32 and X11, a skeleton on Wayland. On platforms without tray or balloon support — polite no-ops.":                                                 "Иконка в трее ставится при старте (синий квадрат с белой «G»). Трей-меню (правый клик): Показать / Свернуть / Balloon / Выход — оно рендерится в собственном окне-попапе у курсора, поэтому появляется даже когда главное окно скрыто. Drag&Drop: Win32 и X11 — нативно, Wayland — каркас. На платформах без поддержки трея/balloon — вежливые no-op.",
	"This is the content of a ScrollViewer. Scroll down to see the whole text. The scroller supports the mouse wheel and dragging the scrollbar. The content height is set through ContentHeight and can exceed the visible area. That makes it possible to place long lists, logs, documentation and any other content of arbitrary length inside a limited area of the screen. The widget works like the WPF ScrollViewer.": "Это содержимое ScrollViewer. Прокрутите вниз чтобы увидеть весь текст. Скроллер поддерживает колёсико мыши и перетаскивание полосы прокрутки. Высота контента задаётся через ContentHeight и может быть больше видимой области. Это позволяет размещать длинные списки, логи, документацию и другой контент произвольной длины внутри ограниченной области экрана. Виджет работает аналогично ScrollViewer из WPF.",
	"Toolbox": "Панель инструментов",
	"Tabbed window": "Окно с вкладками",
	"Window with tabs in the title bar (Windows 11 Terminal style)": "Окно с вкладками в заголовке (стиль Windows 11 Terminal)",
	"Tabs live in the window title bar next to the window buttons: a cross closes a tab, plus opens a new one, the chevron shows the profile menu. Free title-bar space still drags the window. Switch the theme - the tab strip follows Win10/Win11, Win2000 bevel and Mac styles.": "Вкладки живут прямо в заголовке окна рядом с его кнопками: крестик закрывает вкладку, плюс открывает новую, шеврон показывает меню профилей. Свободное место заголовка по-прежнему перетаскивает окно. Переключите тему — полоса вкладок следует стилям Win10/Win11, Win2000 (bevel) и Mac.",
	"The inner window is a real widget.Window with EnableTitleTabs: drag it by the title, resize by the edges, close all tabs - OnClose restores the demo.": "Внутреннее окно — настоящий widget.Window с EnableTitleTabs: тащите за заголовок, меняйте размер за края, закройте все вкладки — OnClose восстановит демо.",
	"Tray · notifications · window preview (Windows only)": "Трей · уведомления · превью окна (только Windows)",
	"Two-way binding": "Двусторонняя привязка",
	"Undo":            "Отменить",
	"Use SSL/TLS":     "Использовать SSL/TLS",
	"User":            "Пользователь",
	"User role:":      "Роль пользователя:",
	"User أحمد (role: מנהל) — active": "User أحمد (роль: מנהל) — активен",
	"Validation (IDataErrorInfo)":     "Валидация (IDataErrorInfo)",
	"Verbose logging":                 "Подробное логирование (verbose)",
	"View":                            "Вид",
	"Volume:":                         "Громкость:",
	"WIDGETS":                         "ВИДЖЕТЫ",
	"Warning":                         "Предупреждение",
	"Widgets live in logical pixels while the frame renders in physical ones. Windows picks up the monitor scale automatically (per-monitor DPI v2). Manual run: HEADLESS_GUI_SCALE=1.5 showcase.exe — the text is rasterised at the physical size instead of being stretched.": "Виджеты живут в логических пикселях, кадр рендерится в физических. Windows: масштаб монитора подхватывается автоматически (per-monitor DPI v2). Ручной запуск: HEADLESS_GUI_SCALE=1.5 showcase.exe — текст растеризуется в физическом размере, а не растягивается.",
	"Widgets: 16": "Виджетов: 16",
	"Window (theme chrome: corners / title / buttons)": "Окно (chrome темы: углы / заголовок / кнопки)",
	"Window and tray:": "Окно и трей:",
	"Without Color the icon takes the theme text colour (switch the theme in the header); with Color it is fixed. Any size — it is a vector.": "Без Color иконка красится под цвет текста темы (переключи тему в шапке); с Color — фиксированный цвет. Размер любой — вектор.",
	"[ Image area — Image Source='path' ]":   "[ Область для изображения — Image Source='path' ]",
	"[09:00:01] Engine started":              "[09:00:01] Движок запущен",
	"[09:00:01] XAML loaded: showcase.xaml":  "[09:00:01] XAML загружен: showcase.xaml",
	"[09:00:02] Connecting to the server...": "[09:00:02] Подключение к серверу...",
	"[09:00:03] Authentication: LDAP":        "[09:00:03] Аутентификация: LDAP",
	"[09:00:03] Connection established":      "[09:00:03] Соединение установлено",
	"[09:00:04] Session opened":              "[09:00:04] Сессия открыта",
	"[09:00:05] Loading the user profile":    "[09:00:05] Загрузка профиля пользователя",
	"[09:00:06] Profile loaded":              "[09:00:06] Профиль загружен",
	"[09:00:07] Initialising the desktop":    "[09:00:07] Инициализация рабочего стола",
	"[09:00:08] Ready":                       "[09:00:08] Готов к работе",
	"↦ New target":                           "↦ Новая цель",
	"⇄ Back and forth":                       "⇄ Туда-обратно",
	"▶ Start the race":                       "▶ Запустить гонку",
}

// Register подключает ОБЕ таблицы переводов: строки разметки
// (эта, сгенерированная) и строки, задаваемые кодом (strings_code_ru.go).
// Запасной язык — английский, но таблицы для него нет: ключ и есть английский
// текст, и Tr возвращает его сам.
func Register() {
	widget.SetFallbackLanguage("EN")
	widget.RegisterStrings("RU", showcaseRU)
	widget.RegisterStrings("RU", showcaseCodeRU)
}
