// strings_code_ru.go — переводы строк, которые showcase создаёт в коде
// (сообщения журнала, диалоги, трей-меню, подписи, собираемые на лету).
//
// Как и в strings_ru.go, ключ — английская строка: в EN-режиме Tr возвращает
// сам ключ. СГЕНЕРИРОВАНО инструментом localize_go, правится вместе с кодом.
package showcasestrings

// showcaseCodeRU — переводы строк, задаваемых из кода.
var showcaseCodeRU = map[string]string{
	"  …and %d more":                                   "  …и ещё %d",
	"%d of 120 files · 61.4 MB/s":                      "%d из 120 файлов · 61,4 МБ/с",
	"3.2.4: Save command executed":                     "3.2.4: команда Save выполнена",
	"3.2.4: row added (live ItemsControl)":             "3.2.4: строка добавлена (live ItemsControl)",
	"3.2.4: status → ERROR (DataTrigger)":              "3.2.4: статус → ERROR (DataTrigger)",
	"3.2.5: Save (localised button)":                   "3.2.5: Save (локализованная кнопка)",
	"3.2.5: TextBox = %q (%d chars)":                   "3.2.5: TextBox = %q (%d симв.)",
	"3.2.5: UI language → EN ({Loc} updated live)":     "3.2.5: язык интерфейса → EN ({Loc} обновлены вживую)",
	"3.2.5: UI language → RU ({Loc} updated live)":     "3.2.5: язык интерфейса → RU ({Loc} обновлены вживую)",
	"3.2.5: filter age ≥ 30 (%d visible)":              "3.2.5: фильтр возраст ≥ 30 (видно %d)",
	"3.2.5: filter and sorting reset (%d)":             "3.2.5: фильтр/сортировка сброшены (%d)",
	"3.2.5: price = %.2f":                              "3.2.5: цена = %.2f",
	"3.2.5: quantity = %.0f":                           "3.2.5: количество = %.0f",
	"3.2.5: sorted by name":                            "3.2.5: сортировка по имени",
	"A notification from the tray menu.":               "Уведомление из трей-меню.",
	"All files":                                        "Все файлы",
	"Audio":                                            "Аудио",
	"Auto-connect":                                     "Автоподключение",
	"Auto-update":                                      "Авто-обновление",
	"Balloon: error shown":                             "Balloon: ошибка показана",
	"Balloon: error — %v":                              "Balloon: ошибка — %v",
	"Balloon: info shown":                              "Balloon: инфо показан",
	"Balloon: warning shown":                           "Balloon: предупреждение показано",
	"Cancel pressed":                                   "Отмена нажата",
	"Cannot open the file (EACCES).":                   "Не удалось открыть файл (EACCES).",
	"Cannot open the file: access denied (EACCES).":    "Не удалось открыть файл: доступ запрещён (EACCES).",
	"Certificate":                                      "Сертификат",
	"Characters: %d · lines (visual): %d":              "Символов: %d · строк (визуальных): %d",
	"Click on the balloon notification":                "Клик по balloon-уведомлению",
	"Close":                                            "Закрыть",
	"Compression":                                      "Сжатие",
	"Copying files":                                    "Копирование файлов",
	"Copying finished":                                 "Копирование завершено",
	"Dark theme":                                       "Тёмная тема",
	"Delete pressed (dangerous action)":                "Удалить нажата (опасное действие)",
	"Dialogs: opened the large 1000x700 dialog":        "Диалоги: открыт большой диалог 1000x700",
	"DockManager: cannot restore the layout: %v":       "DockManager: ошибка восстановления раскладки: %v",
	"DockManager: layout restored":                     "DockManager: раскладка восстановлена",
	"DockManager: layout saved (%d bytes)":             "DockManager: раскладка сохранена (%d байт)",
	"DockManager: restore cancelled — no saved layout": "DockManager: восстановление отменено — нет сохранённой раскладки",
	"Document saved. A backup copy has been created.":  "Документ сохранён. Резервная копия создана.",
	"Drop: %d file(s) at (%d,%d)":                      "Drop: %d файл(ов) в (%d,%d)",
	"Dropped %d at (%d,%d):":                           "Брошено %d в (%d,%d):",
	"E-mail cannot be empty":                           "E-mail не может быть пустым",
	"E-mail must contain @":                            "E-mail должен содержать «@»",
	"Error":                                            "Ошибка",
	"Event added by the user":                          "Событие добавлено пользователем",
	"Exit":                                             "Выход",
	"Exporting settings...":                            "Экспорт настроек...",
	"Folder → %s":                                      "Папка → %s",
	"Form reset":                                       "Форма сброшена",
	"Full screen":                                      "Полноэкранный режим",
	"Hello! Switch the language →":                     "Привет! Переключите язык →",
	"High":                                             "Высокое",
	"Images":                                           "Изображения",
	"Information":                                      "Информация",
	"Inner tab: %s":                                    "Внутренняя вкладка: %s",
	"Input cancelled":                                  "Ввод отменён",
	"Input → %q":                                       "Ввод → %q",
	"Language:":                                        "Язык:",
	"Large dialog in its own window":                   "Большой диалог в собственном окне",
	"Layout restored":                                  "Раскладка восстановлена",
	"Layout saved (%d bytes of JSON)":                  "Раскладка сохранена (%d байт JSON)",
	"Localization (dynamic Loc bindings)":              "Локализация (динамические {Loc})",
	"Log cleared":                                      "Журнал очищен",
	"Low":                                              "Низкое",
	"Medium":                                           "Среднее",
	"Menu: %s (section %d, item %d)":                   "Меню: %s (раздел %d, пункт %d)",
	"Minimise":                                         "Свернуть",
	"New item name:":                                   "Новое имя элемента:",
	"Notifications":                                    "Уведомления",
	"OFF":                                              "ВЫКЛ",
	"ON":                                               "ВКЛ",
	"Open → %s":                                        "Открыть → %s",
	"Playback: %.0f%%":                                 "Воспроизведение: %.0f%%",
	"PopupMenu opened (ShowBelow)":                     "PopupMenu открыто (ShowBelow)",
	"PopupMenu opened (ShowRight)":                     "PopupMenu открыто (ShowRight)",
	"Progress cancelled":                               "Прогресс отменён",
	"Protocol: %s":                                     "Протокол: %s",
	"Question → %v":                                    "Вопрос → %v",
	"Ready — Ctrl+S to save":                           "Готов — Ctrl+S для сохранения",
	"Recording: %.0f%%":                                "Запись: %.0f%%",
	"Remember":                                         "Запомнить",
	"Restore failed: %s":                               "Ошибка восстановления: %s",
	"Role: %s":                                         "Роль: %s",
	"Save":                                             "Сохранить",
	"Save the changes before exiting?":                 "Сохранить изменения перед выходом?",
	"Save the layout first":                            "Сначала сохрани раскладку",
	"Save → %s":                                        "Сохранить → %s",
	"Saved at %s":                                      "Сохранено в %s",
	"Scale: %.0f%%  ·  logical %d×%d → physical %d×%d": "Масштаб: %.0f%%  ·  логический %d×%d → физический %d×%d",
	"Show":                     "Показать",
	"Sign in: user=%s":         "Вход: user=%s",
	"Smoothing":                "Сглаживание",
	"SplitPanel: collapsed=%v": "SplitPanel: коллапс=%v",
	"Spreadsheets":             "Таблицы",
	"Switch the UI language (not the keyboard layout)": "Сменить язык интерфейса (не раскладку клавиатуры)",
	"System properties": "Свойства системы",
	"Tab: %s (%d)":      "Вкладка: %s (%d)",
	"The buttons change the UI language (widget.Language) — Loc strings update live": "Кнопки меняют язык интерфейса (widget.Language) — строки {Loc} обновляются вживую",
	"The name cannot contain / \\ : * ?":                                             "Имя не может содержать / \\ : * ?",
	"The operation completed successfully.":                                          "Операция выполнена успешно.",
	"Theme: %s":                                                                      "Тема: %s",
	"There are unsaved changes.":                                                     "Есть несохранённые изменения.",
	"This feature is available on Windows only.":                                     "Эта функция доступна только в Windows.",
	"Tray menu: %s":                                                                  "Трей-меню: %s",
	"UI language → %s":                                                               "Язык интерфейса → %s",
	"Unsaved changes will be lost.":                                                  "Несохранённые изменения будут потеряны.",
	"Verifying checksums…":                                                           "Проверка контрольных сумм…",
	"Warning":                                                                        "Предупреждение",
	"Window minimised to the tray (double left click on the icon restores it)": "Окно свёрнуто в трей (двойной левый клик по иконке — восстановить)",
	"cannot load showcase.xaml: %v":                                            "ошибка загрузки showcase.xaml: %v",
	"tray icon unavailable: %v":                                                "трей-иконка недоступна: %v",
	"This dialog is 1000×700. Since v3.10 modal dialogs open in a separate native OS window, so they can be larger than the main window and can be dragged outside it.":                                                                                                                             "Этот диалог — 1000×700. Начиная с v3.10 модальные диалоги открываются в отдельном нативном окне ОС, поэтому могут быть больше главного окна и перетаскиваться за его пределы.",
	"The multiline editor of the engine.\n\nWord wrapping, vertical scrolling with the wheel and PgUp/PgDn, selection with the mouse and Shift+arrows, Ctrl+arrows — by words, Ctrl+Home/End — document bounds, Ctrl+C/X/V and Ctrl+Z/Y.\n\nMixed content: English, Russian and digits 1234567890.": "Многострочный редактор движка.\n\nПеренос по словам, вертикальный скролл колесом и PgUp/PgDn, выделение мышью и Shift+стрелками, Ctrl+стрелки — по словам, Ctrl+Home/End — границы документа, Ctrl+C/X/V и Ctrl+Z/Y.\n\nMixed content: English, русский и цифры 1234567890.",
	"This field is ReadOnly: the text can be selected and copied (Ctrl+C, context menu) but not edited.\n\nThe editor works headless too: input arrives through SendKeyEvent and layout is computed without a window.":                                                                              "Это поле ReadOnly: текст можно выделять и копировать (Ctrl+C, контекстное меню), но не редактировать.\n\nРедактор работает и в headless-режиме: ввод приходит через SendKeyEvent, компоновка считается без окна.",
}
